# A sample Gemfile
source "https://rubygems.org"

group :development do
  gem "awesome_print"
  gem "rspec"
  gem "rake"
  gem "guard"
  gem "guard-bundler"
  gem "guard-rspec"
  gem "rb-fsevent"
end
